server:
  port: 8080
  servlet:
    context-path: /bigprime-data

spring:
  profiles:
    active: dev  # 默认激活开发环境配置

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  # Redis 基础配置（可被子配置覆盖）
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    database: 0
    password:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 推荐使用 slf4j 统一日志
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hengheng.basicframework.entity

logging:
  level:
    root: info
    com.hengheng: info

