server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://10.10.10.242:3306/bigprime?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mairunQ!@#123

  data:
    mongodb:
      uri: mongodb://mairun:mairun123@47.108.155.61:27017
      database: mairun_mes
  redis:
    host: 10.10.10.242
    port: 16379
    database: 1
    password:

logging:
  level:
    root: info
