server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://10.10.10.242:3306/bigprime?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mairunQ!@#123

  redis:
    host: 10.10.10.242
    port: 16379
    database: 1
    password:

logging:
  level:
    root: info
